name: CI with Trello

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test
        run: |
          ./mvnw clean test

      - name: Notify Trello (success)
        if: success()
        run: |
          curl -X POST "https://api.trello.com/1/cards/${{ secrets.TRELLO_CARD_ID }}/actions/comments" \
          -d "text=✅ Build passed for commit $GITHUB_SHA" \
          -d "key=${{ secrets.TRELLO_API_KEY }}" \
          -d "token=${{ secrets.TRELLO_TOKEN }}"

      - name: Notify Trello (failure)
        if: failure()
        run: |
          curl -X POST "https://api.trello.com/1/cards/${{ secrets.TRELLO_CARD_ID }}/actions/comments" \
          -d "text=❌ Build failed for commit $GITHUB_SHA" \
          -d "key=${{ secrets.TRELLO_API_KEY }}" \
          -d "token=${{ secrets.TRELLO_TOKEN }}"
